import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Ubuntu, Prompt } from 'next/font/google'
import Providers from './providers'
const ubuntu = Ubuntu({ subsets: ['latin'], weight: ["400", "700"], variable: "--font-ubuntu" })
const prompt = Prompt({ subsets: ['latin'], weight: ["400", "700"], variable: "--font-prompt" })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <body className={`${ubuntu.className}`}>
        <Providers>{children}
        </Providers>
      </body>
    </html>
  )
}
